Add blog post to announce python-tuf 1.0.0 release
secure-systems-lab/ssl-site pull request #136
Opened 2022-02-17 14:09 UTC by lukpueh

2022-02-17 14:09 UTC, lukpueh commented
cc @jku

2022-02-17 15:55 UTC, jhdalek55 requested changes

2022-02-17 15:55 UTC, jhdalek55 commented on _posts/2022-02-21-tuf-1_0_0.md
> +- The implementation details are now easier to reason about which should
Add comma after "reason about"

2022-02-17 15:55 UTC, jhdalek55 commented on _posts/2022-02-21-tuf-1_0_0.md
> +steps. You can expect at least improved repository side tooling but we’re open
At the very least, you can expect improved repository side tooling, but we're also open to new ideas. Pop in to

2022-02-18 13:47 UTC, jku commented on _posts/2022-02-21-tuf-1_0_0.md
> +- [`Metadata API`](https://theupdateframework.readthedocs.io/en/v0.20.0/api/tuf.api.html):
```suggestion
- [`Metadata API`](https://theupdateframework.readthedocs.io/en/latest/api/tuf.api.html):
```
I fixed this in the google doc already

2022-02-18 15:42 UTC, jhdalek55 commented
LGTM--I think its ready to post

2022-02-21 08:37 UTC, JustinCappos approved these changes

2022-02-21 08:42 UTC, merged